name: Documentation Validation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/docs-validation.yml'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/docs-validation.yml'
      - 'package.json'
      - 'package-lock.json'

jobs:
  validate-docs:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Validate documentation
        run: |
          echo "Running documentation validation..."
          npm run validate-docs
          npm run check-doc-references
          npm run validate-mermaid
          npm run validate-frontmatter
          
      - name: Upload validation results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docs-validation-results
          path: |
            docs-validation.log
            mermaid-validation.log
            frontmatter-validation.log
          retention-days: 7 